// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GreetsColumns holds the columns for the "greets" table.
	GreetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GreetsTable holds the schema information for the "greets" table.
	GreetsTable = &schema.Table{
		Name:       "greets",
		Columns:    GreetsColumns,
		PrimaryKey: []*schema.Column{GreetsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GreetsTable,
	}
)

func init() {
}
