// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: demo/v1/demo.proto

// Package demo.v1 holds the demo service contract.
//
// T2 落地真正的 DemoService：保留 T1 的 Ping（最小可生成 + liveness echo），
// 新增 GetGreet（经数据层读 greet，用于后续 PG 弹性闭环验证）。
// 错误模型（reason 枚举 + kratos errors 注解）在 error_reason.proto。

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HitsRequest is the request for Hits.
type HitsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is an optional counter key. When empty the server uses the default
	// counter "demo:hits". A non-empty key increments that named counter instead
	// (e.g. ?key=foo bumps "foo"). The key must be at most 128 bytes and contain
	// no control or whitespace characters; otherwise INVALID_ARGUMENT (HTTP 400).
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitsRequest) Reset() {
	*x = HitsRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitsRequest) ProtoMessage() {}

func (x *HitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitsRequest.ProtoReflect.Descriptor instead.
func (*HitsRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{0}
}

func (x *HitsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// HitsReply is the response for Hits.
type HitsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// count is the current value of the hit counter after incrementing.
	Count         int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitsReply) Reset() {
	*x = HitsReply{}
	mi := &file_demo_v1_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitsReply) ProtoMessage() {}

func (x *HitsReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitsReply.ProtoReflect.Descriptor instead.
func (*HitsReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{1}
}

func (x *HitsReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// PingRequest is the request for Ping.
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is an optional caller label echoed back.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PingResponse is the response for Ping.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message echoes a greeting back to the caller.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_demo_v1_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetGreetRequest is the request for GetGreet.
type GetGreetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id identifies the greet to fetch.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGreetRequest) Reset() {
	*x = GetGreetRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetRequest) ProtoMessage() {}

func (x *GetGreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetRequest.ProtoReflect.Descriptor instead.
func (*GetGreetRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{4}
}

func (x *GetGreetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Greet is a single greeting record.
type Greet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the greet identifier.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// content is the greeting text.
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Greet) Reset() {
	*x = Greet{}
	mi := &file_demo_v1_demo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Greet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greet) ProtoMessage() {}

func (x *Greet) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greet.ProtoReflect.Descriptor instead.
func (*Greet) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{5}
}

func (x *Greet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Greet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// PublishEventRequest carries the event payload to publish.
type PublishEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the raw event body. Must not be empty.
	Payload       string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{6}
}

func (x *PublishEventRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// PublishEventReply carries the generated event id.
type PublishEventReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier assigned to the published event.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventReply) Reset() {
	*x = PublishEventReply{}
	mi := &file_demo_v1_demo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventReply) ProtoMessage() {}

func (x *PublishEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventReply.ProtoReflect.Descriptor instead.
func (*PublishEventReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{7}
}

func (x *PublishEventReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_demo_v1_demo_proto protoreflect.FileDescriptor

const file_demo_v1_demo_proto_rawDesc = "" +
	"\n" +
	"\x12demo/v1/demo.proto\x12\ademo.v1\x1a\x1cgoogle/api/annotations.proto\"\x1f\n" +
	"\vHitsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"!\n" +
	"\tHitsReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\x0fGetGreetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x05Greet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"/\n" +
	"\x13PublishEventRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"#\n" +
	"\x11PublishEventReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xc7\x02\n" +
	"\vDemoService\x12E\n" +
	"\x04Ping\x12\x14.demo.v1.PingRequest\x1a\x15.demo.v1.PingResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/ping\x12L\n" +
	"\bGetGreet\x12\x18.demo.v1.GetGreetRequest\x1a\x0e.demo.v1.Greet\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/greet/{id}\x12B\n" +
	"\x04Hits\x12\x14.demo.v1.HitsRequest\x1a\x12.demo.v1.HitsReply\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/hits\x12_\n" +
	"\fPublishEvent\x12\x1c.demo.v1.PublishEventRequest\x1a\x1a.demo.v1.PublishEventReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/eventsB\x83\x01\n" +
	"\vcom.demo.v1B\tDemoProtoP\x01Z,github.com/z-mate/kratos-base/api/demo/v1;v1\xa2\x02\x03DXX\xaa\x02\aDemo.V1\xca\x02\aDemo\\V1\xe2\x02\x13Demo\\V1\\GPBMetadata\xea\x02\bDemo::V1b\x06proto3"

var (
	file_demo_v1_demo_proto_rawDescOnce sync.Once
	file_demo_v1_demo_proto_rawDescData []byte
)

func file_demo_v1_demo_proto_rawDescGZIP() []byte {
	file_demo_v1_demo_proto_rawDescOnce.Do(func() {
		file_demo_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_v1_demo_proto_rawDesc), len(file_demo_v1_demo_proto_rawDesc)))
	})
	return file_demo_v1_demo_proto_rawDescData
}

var file_demo_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_demo_v1_demo_proto_goTypes = []any{
	(*HitsRequest)(nil),         // 0: demo.v1.HitsRequest
	(*HitsReply)(nil),           // 1: demo.v1.HitsReply
	(*PingRequest)(nil),         // 2: demo.v1.PingRequest
	(*PingResponse)(nil),        // 3: demo.v1.PingResponse
	(*GetGreetRequest)(nil),     // 4: demo.v1.GetGreetRequest
	(*Greet)(nil),               // 5: demo.v1.Greet
	(*PublishEventRequest)(nil), // 6: demo.v1.PublishEventRequest
	(*PublishEventReply)(nil),   // 7: demo.v1.PublishEventReply
}
var file_demo_v1_demo_proto_depIdxs = []int32{
	2, // 0: demo.v1.DemoService.Ping:input_type -> demo.v1.PingRequest
	4, // 1: demo.v1.DemoService.GetGreet:input_type -> demo.v1.GetGreetRequest
	0, // 2: demo.v1.DemoService.Hits:input_type -> demo.v1.HitsRequest
	6, // 3: demo.v1.DemoService.PublishEvent:input_type -> demo.v1.PublishEventRequest
	3, // 4: demo.v1.DemoService.Ping:output_type -> demo.v1.PingResponse
	5, // 5: demo.v1.DemoService.GetGreet:output_type -> demo.v1.Greet
	1, // 6: demo.v1.DemoService.Hits:output_type -> demo.v1.HitsReply
	7, // 7: demo.v1.DemoService.PublishEvent:output_type -> demo.v1.PublishEventReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo_v1_demo_proto_init() }
func file_demo_v1_demo_proto_init() {
	if File_demo_v1_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_v1_demo_proto_rawDesc), len(file_demo_v1_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_v1_demo_proto_goTypes,
		DependencyIndexes: file_demo_v1_demo_proto_depIdxs,
		MessageInfos:      file_demo_v1_demo_proto_msgTypes,
	}.Build()
	File_demo_v1_demo_proto = out.File
	file_demo_v1_demo_proto_goTypes = nil
	file_demo_v1_demo_proto_depIdxs = nil
}
