// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: demo/v1/demo.proto

// Package demo.v1 holds the demo service contract.
//
// T2 落地真正的 DemoService：保留 T1 的 Ping（最小可生成 + liveness echo），
// 新增 GetGreet（经数据层读 greet，用于后续 PG 弹性闭环验证）。
// 错误模型（reason 枚举 + kratos errors 注解）在 error_reason.proto。

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DemoService_Ping_FullMethodName         = "/demo.v1.DemoService/Ping"
	DemoService_GetGreet_FullMethodName     = "/demo.v1.DemoService/GetGreet"
	DemoService_Hits_FullMethodName         = "/demo.v1.DemoService/Hits"
	DemoService_PublishEvent_FullMethodName = "/demo.v1.DemoService/PublishEvent"
)

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DemoService is the demo service contract for the kratos-base spine.
type DemoServiceClient interface {
	// Ping is a trivial liveness echo; pure in-memory, no external dependency.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// GetGreet returns a greeting by id; backed by the data layer (PostgreSQL/ent).
	// On dependency outage it returns a DB_UNAVAILABLE error (see error_reason.proto)
	// without crashing the service.
	GetGreet(ctx context.Context, in *GetGreetRequest, opts ...grpc.CallOption) (*Greet, error)
	// Hits increments and returns a Redis-backed hit counter.
	// On Redis outage it returns a DB_UNAVAILABLE error (HTTP 503) without
	// crashing the service.
	Hits(ctx context.Context, in *HitsRequest, opts ...grpc.CallOption) (*HitsReply, error)
	// PublishEvent publishes an arbitrary payload to the configured MQ topic.
	// Returns DB_UNAVAILABLE (HTTP 503) when the broker is unreachable or MQ is
	// not enabled. Returns INVALID_ARGUMENT (HTTP 400) when payload is empty.
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventReply, error)
}

type demoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoServiceClient(cc grpc.ClientConnInterface) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DemoService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoServiceClient) GetGreet(ctx context.Context, in *GetGreetRequest, opts ...grpc.CallOption) (*Greet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Greet)
	err := c.cc.Invoke(ctx, DemoService_GetGreet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoServiceClient) Hits(ctx context.Context, in *HitsRequest, opts ...grpc.CallOption) (*HitsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HitsReply)
	err := c.cc.Invoke(ctx, DemoService_Hits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoServiceClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventReply)
	err := c.cc.Invoke(ctx, DemoService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServiceServer is the server API for DemoService service.
// All implementations should embed UnimplementedDemoServiceServer
// for forward compatibility.
//
// DemoService is the demo service contract for the kratos-base spine.
type DemoServiceServer interface {
	// Ping is a trivial liveness echo; pure in-memory, no external dependency.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// GetGreet returns a greeting by id; backed by the data layer (PostgreSQL/ent).
	// On dependency outage it returns a DB_UNAVAILABLE error (see error_reason.proto)
	// without crashing the service.
	GetGreet(context.Context, *GetGreetRequest) (*Greet, error)
	// Hits increments and returns a Redis-backed hit counter.
	// On Redis outage it returns a DB_UNAVAILABLE error (HTTP 503) without
	// crashing the service.
	Hits(context.Context, *HitsRequest) (*HitsReply, error)
	// PublishEvent publishes an arbitrary payload to the configured MQ topic.
	// Returns DB_UNAVAILABLE (HTTP 503) when the broker is unreachable or MQ is
	// not enabled. Returns INVALID_ARGUMENT (HTTP 400) when payload is empty.
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventReply, error)
}

// UnimplementedDemoServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemoServiceServer struct{}

func (UnimplementedDemoServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDemoServiceServer) GetGreet(context.Context, *GetGreetRequest) (*Greet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGreet not implemented")
}
func (UnimplementedDemoServiceServer) Hits(context.Context, *HitsRequest) (*HitsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Hits not implemented")
}
func (UnimplementedDemoServiceServer) PublishEvent(context.Context, *PublishEventRequest) (*PublishEventReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedDemoServiceServer) testEmbeddedByValue() {}

// UnsafeDemoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoServiceServer will
// result in compilation errors.
type UnsafeDemoServiceServer interface {
	mustEmbedUnimplementedDemoServiceServer()
}

func RegisterDemoServiceServer(s grpc.ServiceRegistrar, srv DemoServiceServer) {
	// If the following call panics, it indicates UnimplementedDemoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DemoService_ServiceDesc, srv)
}

func _DemoService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoService_GetGreet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).GetGreet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoService_GetGreet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).GetGreet(ctx, req.(*GetGreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoService_Hits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).Hits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoService_Hits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).Hits(ctx, req.(*HitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DemoService_ServiceDesc is the grpc.ServiceDesc for DemoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.v1.DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DemoService_Ping_Handler,
		},
		{
			MethodName: "GetGreet",
			Handler:    _DemoService_GetGreet_Handler,
		},
		{
			MethodName: "Hits",
			Handler:    _DemoService_Hits_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _DemoService_PublishEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo/v1/demo.proto",
}
