// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: demo/v1/demo.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDemoServiceGetGreet = "/demo.v1.DemoService/GetGreet"
const OperationDemoServiceHits = "/demo.v1.DemoService/Hits"
const OperationDemoServicePing = "/demo.v1.DemoService/Ping"
const OperationDemoServicePublishEvent = "/demo.v1.DemoService/PublishEvent"

type DemoServiceHTTPServer interface {
	// GetGreet GetGreet returns a greeting by id; backed by the data layer (PostgreSQL/ent).
	// On dependency outage it returns a DB_UNAVAILABLE error (see error_reason.proto)
	// without crashing the service.
	GetGreet(context.Context, *GetGreetRequest) (*Greet, error)
	// Hits Hits increments and returns a Redis-backed hit counter.
	// On Redis outage it returns a DB_UNAVAILABLE error (HTTP 503) without
	// crashing the service.
	Hits(context.Context, *HitsRequest) (*HitsReply, error)
	// Ping Ping is a trivial liveness echo; pure in-memory, no external dependency.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// PublishEvent PublishEvent publishes an arbitrary payload to the configured MQ topic.
	// Returns DB_UNAVAILABLE (HTTP 503) when the broker is unreachable or MQ is
	// not enabled. Returns INVALID_ARGUMENT (HTTP 400) when payload is empty.
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventReply, error)
}

func RegisterDemoServiceHTTPServer(s *http.Server, srv DemoServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/ping", _DemoService_Ping0_HTTP_Handler(srv))
	r.GET("/v1/greet/{id}", _DemoService_GetGreet0_HTTP_Handler(srv))
	r.GET("/v1/hits", _DemoService_Hits0_HTTP_Handler(srv))
	r.POST("/v1/events", _DemoService_PublishEvent0_HTTP_Handler(srv))
}

func _DemoService_Ping0_HTTP_Handler(srv DemoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDemoServicePing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*PingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingResponse)
		return ctx.Result(200, reply)
	}
}

func _DemoService_GetGreet0_HTTP_Handler(srv DemoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGreetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDemoServiceGetGreet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGreet(ctx, req.(*GetGreetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Greet)
		return ctx.Result(200, reply)
	}
}

func _DemoService_Hits0_HTTP_Handler(srv DemoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HitsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDemoServiceHits)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Hits(ctx, req.(*HitsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HitsReply)
		return ctx.Result(200, reply)
	}
}

func _DemoService_PublishEvent0_HTTP_Handler(srv DemoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDemoServicePublishEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishEvent(ctx, req.(*PublishEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishEventReply)
		return ctx.Result(200, reply)
	}
}

type DemoServiceHTTPClient interface {
	// GetGreet GetGreet returns a greeting by id; backed by the data layer (PostgreSQL/ent).
	// On dependency outage it returns a DB_UNAVAILABLE error (see error_reason.proto)
	// without crashing the service.
	GetGreet(ctx context.Context, req *GetGreetRequest, opts ...http.CallOption) (rsp *Greet, err error)
	// Hits Hits increments and returns a Redis-backed hit counter.
	// On Redis outage it returns a DB_UNAVAILABLE error (HTTP 503) without
	// crashing the service.
	Hits(ctx context.Context, req *HitsRequest, opts ...http.CallOption) (rsp *HitsReply, err error)
	// Ping Ping is a trivial liveness echo; pure in-memory, no external dependency.
	Ping(ctx context.Context, req *PingRequest, opts ...http.CallOption) (rsp *PingResponse, err error)
	// PublishEvent PublishEvent publishes an arbitrary payload to the configured MQ topic.
	// Returns DB_UNAVAILABLE (HTTP 503) when the broker is unreachable or MQ is
	// not enabled. Returns INVALID_ARGUMENT (HTTP 400) when payload is empty.
	PublishEvent(ctx context.Context, req *PublishEventRequest, opts ...http.CallOption) (rsp *PublishEventReply, err error)
}

type DemoServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDemoServiceHTTPClient(client *http.Client) DemoServiceHTTPClient {
	return &DemoServiceHTTPClientImpl{client}
}

// GetGreet GetGreet returns a greeting by id; backed by the data layer (PostgreSQL/ent).
// On dependency outage it returns a DB_UNAVAILABLE error (see error_reason.proto)
// without crashing the service.
func (c *DemoServiceHTTPClientImpl) GetGreet(ctx context.Context, in *GetGreetRequest, opts ...http.CallOption) (*Greet, error) {
	var out Greet
	pattern := "/v1/greet/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDemoServiceGetGreet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Hits Hits increments and returns a Redis-backed hit counter.
// On Redis outage it returns a DB_UNAVAILABLE error (HTTP 503) without
// crashing the service.
func (c *DemoServiceHTTPClientImpl) Hits(ctx context.Context, in *HitsRequest, opts ...http.CallOption) (*HitsReply, error) {
	var out HitsReply
	pattern := "/v1/hits"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDemoServiceHits))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Ping Ping is a trivial liveness echo; pure in-memory, no external dependency.
func (c *DemoServiceHTTPClientImpl) Ping(ctx context.Context, in *PingRequest, opts ...http.CallOption) (*PingResponse, error) {
	var out PingResponse
	pattern := "/v1/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDemoServicePing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PublishEvent PublishEvent publishes an arbitrary payload to the configured MQ topic.
// Returns DB_UNAVAILABLE (HTTP 503) when the broker is unreachable or MQ is
// not enabled. Returns INVALID_ARGUMENT (HTTP 400) when payload is empty.
func (c *DemoServiceHTTPClientImpl) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...http.CallOption) (*PublishEventReply, error) {
	var out PublishEventReply
	pattern := "/v1/events"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDemoServicePublishEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
