// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: demo/v1/error_reason.proto

// Package demo.v1 — error reason model for the demo domain.
//
// 每个枚举值的名字即 kratos error 的 `reason` 字符串（生成的构造器/判定用
// `EnumValue.String()`）。故这里的值名保持业务约定的裸命名
// （DB_UNAVAILABLE / NOT_FOUND / INVALID_ARGUMENT），不加 `ERROR_REASON_` 前缀，
// 否则 reason 字符串会带上前缀、与契约不符。buf.yaml 顶层 except 掉
// ENUM_VALUE_PREFIX 正是为此。零值 ERROR_REASON_UNSPECIFIED 已以 _UNSPECIFIED
// 结尾、本就合规，无需豁免 ENUM_ZERO_VALUE_SUFFIX。
//
// protoc-gen-go-errors 为每个有效 code 的枚举值生成 Is*/Error* 助手。
// 零值 ERROR_REASON_UNSPECIFIED 无 (errors.code) 覆盖，继承 default_code=500，
// 故也会生成助手（reason "ERROR_REASON_UNSPECIFIED"）；pkg/errs 不导出它。

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason enumerates the demo service's well-known error reasons.
// 默认 HTTP code 500；每个值用 (errors.code) 覆盖为具体状态码。
type ErrorReason int32

const (
	// ERROR_REASON_UNSPECIFIED is the proto3 zero value; not a real reason.
	// It has no (errors.code) override and so inherits default_code 500.
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// DB_UNAVAILABLE: a backing datastore (e.g. PostgreSQL) is unreachable.
	// 懒加载依赖未就绪 / 断线时返回；服务不宕、快速失败。
	ErrorReason_DB_UNAVAILABLE ErrorReason = 1
	// NOT_FOUND: the requested resource does not exist.
	ErrorReason_NOT_FOUND ErrorReason = 2
	// INVALID_ARGUMENT: the caller supplied a malformed or out-of-range argument.
	ErrorReason_INVALID_ARGUMENT ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "DB_UNAVAILABLE",
		2: "NOT_FOUND",
		3: "INVALID_ARGUMENT",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"DB_UNAVAILABLE":           1,
		"NOT_FOUND":                2,
		"INVALID_ARGUMENT":         3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_demo_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_demo_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_demo_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_demo_v1_error_reason_proto protoreflect.FileDescriptor

const file_demo_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1ademo/v1/error_reason.proto\x12\ademo.v1\x1a\x13errors/errors.proto*|\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x0eDB_UNAVAILABLE\x10\x01\x1a\x04\xa8E\xf7\x03\x12\x13\n" +
	"\tNOT_FOUND\x10\x02\x1a\x04\xa8E\x94\x03\x12\x1a\n" +
	"\x10INVALID_ARGUMENT\x10\x03\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03B\x8a\x01\n" +
	"\vcom.demo.v1B\x10ErrorReasonProtoP\x01Z,github.com/z-mate/kratos-base/api/demo/v1;v1\xa2\x02\x03DXX\xaa\x02\aDemo.V1\xca\x02\aDemo\\V1\xe2\x02\x13Demo\\V1\\GPBMetadata\xea\x02\bDemo::V1b\x06proto3"

var (
	file_demo_v1_error_reason_proto_rawDescOnce sync.Once
	file_demo_v1_error_reason_proto_rawDescData []byte
)

func file_demo_v1_error_reason_proto_rawDescGZIP() []byte {
	file_demo_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_demo_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_v1_error_reason_proto_rawDesc), len(file_demo_v1_error_reason_proto_rawDesc)))
	})
	return file_demo_v1_error_reason_proto_rawDescData
}

var file_demo_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_demo_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: demo.v1.ErrorReason
}
var file_demo_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo_v1_error_reason_proto_init() }
func file_demo_v1_error_reason_proto_init() {
	if File_demo_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_v1_error_reason_proto_rawDesc), len(file_demo_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_demo_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_demo_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_demo_v1_error_reason_proto_enumTypes,
	}.Build()
	File_demo_v1_error_reason_proto = out.File
	file_demo_v1_error_reason_proto_goTypes = nil
	file_demo_v1_error_reason_proto_depIdxs = nil
}
