// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// ERROR_REASON_UNSPECIFIED is the proto3 zero value; not a real reason.
// It has no (errors.code) override and so inherits default_code 500.
func IsErrorReasonUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ERROR_REASON_UNSPECIFIED.String() && e.Code == 500
}

// ERROR_REASON_UNSPECIFIED is the proto3 zero value; not a real reason.
// It has no (errors.code) override and so inherits default_code 500.
func ErrorErrorReasonUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_ERROR_REASON_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

// DB_UNAVAILABLE: a backing datastore (e.g. PostgreSQL) is unreachable.
// 懒加载依赖未就绪 / 断线时返回；服务不宕、快速失败。
func IsDbUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_UNAVAILABLE.String() && e.Code == 503
}

// DB_UNAVAILABLE: a backing datastore (e.g. PostgreSQL) is unreachable.
// 懒加载依赖未就绪 / 断线时返回；服务不宕、快速失败。
func ErrorDbUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ErrorReason_DB_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}

// NOT_FOUND: the requested resource does not exist.
func IsNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NOT_FOUND.String() && e.Code == 404
}

// NOT_FOUND: the requested resource does not exist.
func ErrorNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// INVALID_ARGUMENT: the caller supplied a malformed or out-of-range argument.
func IsInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_ARGUMENT.String() && e.Code == 400
}

// INVALID_ARGUMENT: the caller supplied a malformed or out-of-range argument.
func ErrorInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}
