// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/z-mate/kratos-base/app/demo/internal/data/ent/greet"
	"github.com/z-mate/kratos-base/app/demo/internal/data/ent/predicate"
)

// GreetUpdate is the builder for updating Greet entities.
type GreetUpdate struct {
	config
	hooks    []Hook
	mutation *GreetMutation
}

// Where appends a list predicates to the GreetUpdate builder.
func (_u *GreetUpdate) Where(ps ...predicate.Greet) *GreetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *GreetUpdate) SetContent(v string) *GreetUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *GreetUpdate) SetNillableContent(v *string) *GreetUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// Mutation returns the GreetMutation object of the builder.
func (_u *GreetUpdate) Mutation() *GreetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GreetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GreetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GreetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GreetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GreetUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := greet.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Greet.content": %w`, err)}
		}
	}
	return nil
}

func (_u *GreetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(greet.Table, greet.Columns, sqlgraph.NewFieldSpec(greet.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(greet.FieldContent, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{greet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GreetUpdateOne is the builder for updating a single Greet entity.
type GreetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GreetMutation
}

// SetContent sets the "content" field.
func (_u *GreetUpdateOne) SetContent(v string) *GreetUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *GreetUpdateOne) SetNillableContent(v *string) *GreetUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// Mutation returns the GreetMutation object of the builder.
func (_u *GreetUpdateOne) Mutation() *GreetMutation {
	return _u.mutation
}

// Where appends a list predicates to the GreetUpdate builder.
func (_u *GreetUpdateOne) Where(ps ...predicate.Greet) *GreetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GreetUpdateOne) Select(field string, fields ...string) *GreetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Greet entity.
func (_u *GreetUpdateOne) Save(ctx context.Context) (*Greet, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GreetUpdateOne) SaveX(ctx context.Context) *Greet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GreetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GreetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GreetUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := greet.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Greet.content": %w`, err)}
		}
	}
	return nil
}

func (_u *GreetUpdateOne) sqlSave(ctx context.Context) (_node *Greet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(greet.Table, greet.Columns, sqlgraph.NewFieldSpec(greet.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Greet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, greet.FieldID)
		for _, f := range fields {
			if !greet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != greet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(greet.FieldContent, field.TypeString, value)
	}
	_node = &Greet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{greet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
