// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/z-mate/kratos-base/app/demo/internal/data/ent/greet"
	"github.com/z-mate/kratos-base/app/demo/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	greetFields := schema.Greet{}.Fields()
	_ = greetFields
	// greetDescContent is the schema descriptor for content field.
	greetDescContent := greetFields[0].Descriptor()
	// greet.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	greet.ContentValidator = greetDescContent.Validators[0].(func(string) error)
	// greetDescCreatedAt is the schema descriptor for created_at field.
	greetDescCreatedAt := greetFields[1].Descriptor()
	// greet.DefaultCreatedAt holds the default value on creation for the created_at field.
	greet.DefaultCreatedAt = greetDescCreatedAt.Default.(func() time.Time)
}
